version: '3.8'

services:
  arangodb:
    image: arangodb:3.10
    environment:
      - ARANGO_ROOT_PASSWORD=password
    ports:
      - "8529:8529"
    volumes:
      - arango_data:/var/lib/arangodb3

  python-app:
    build: .
    depends_on:
      - arangodb
    environment:
      - ARANGO_HOST=arangodb
      - ARANGO_PORT=8529
    volumes:
      - .:/app
    command: poetry run python gighunt/app.py

volumes:
  arango_data:
