version: '3.8'

services:
  arangodb:
    image: arangodb:3.10
    environment:
      - ARANGO_ROOT_PASSWORD=password
    ports:
      - "8529:8529"
    volumes:
      - arango_data:/var/lib/arangodb3

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - arangodb
    environment:
      - ARANGO_HOST=arangodb
      - ARANGO_PORT=8529
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  arango_data:
